movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'

urlpatterns = [
    path("", views.index, name='index'),
    path('<int:movie_id>', views.detail, name='detail'),
    path("genre/<int:genre_id>", views.filter_genre, name='genre')
]

myfirstsite/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls'), name='movies')
]

movies/models.py
from django.db import models
from django.utils import timezone


class Genre(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Movie(models.Model):
    tmdb_id = models.IntegerField()
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    rating = models.FloatField()
    genre = models.ManyToManyField(Genre)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Movie, Genre
from tmdb_data import get_movie_poster, get_movie_video, get_movie_data


def index(request):
    movies = Movie.objects.all()
    genres = Genre.objects.all()
    return render(request, 'movies/index.html', {'movies': movies, 'genres': genres})


def filter_genre(request, genre_id):
    movies = Movie.objects.filter(genre=genre_id)
    genres = Genre.objects.all()
    return render(request, 'movies/index.html', {'movies': movies, 'genres': genres})


def detail(request, movie_id):
    movie = get_object_or_404(Movie, id=movie_id)
    poster = get_movie_poster(movie.tmdb_id)
    video = get_movie_video(movie.tmdb_id)
    movie_budget = get_movie_data(movie.tmdb_id, 'budget')
    return render(request, 'movies/detail.html', {'movie': movie, 'movie_poster': poster, 'video_key': video, 'movie_budget': movie_budget})

myfirstsite/views.py
from django.shortcuts import render
from movies.views import index


def home(request):
    return index(request)

movies/templates/home.html
{% extends 'base.html' %}

{% block content %}
<a href="{% url 'movies:index' %}" style="text-decoration:none">movies</a>
{% endblock %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
<br>
<br>
<br>
<br>
<br>
<div class="container p-3 mb-2 bg-secondary text-white">
    <div class="row">
        <div class="col-3">
            <img src="{{ movie_poster }}" alt="" width="200">
            <br>
            <br>
            <dl>
                <dt>● Title</dt>
                <dd>{{ movie.title }}</dd>
                <dt>● Release year</dt>
                <dd>{{ movie.release_year }}</dd>
                <dt>● Rating</dt>
                <dd><strong>{{ movie.rating }}</strong>/10</dd>
                <div class="row">
                    <div class="col-md">
                        <dt>● Genre</dt>
                        <dd>{% for mg in movie.genre.all %}. {{ mg }} {% endfor %}</dd>
                    </div>
                    <div class="col-5">
                        <dt>● Budget</dt>
                        <dd>{{ movie_budget }}$</dd>
                    </div>
                </div>
            </dl>
        </div>
        <div class="media col-9">
            <iframe width="910" height="440" src="https://www.youtube.com/embed/{{ video_key }}" frameborder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
        </div><br>
    </div>
</div>

{% endblock %}

movies/templates/movies/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="list-group col-">
        <a href="{% url 'home' %}" class="list-group-item list-group-item-action text-center bg-white">
            All Genres
        </a>
        {% for genre in genres %}
        <a href="{% url 'movies:genre' genre.id %} " class="list-group-item list-group-item-action">{{ genre }}</a>
        {% endfor %}
    </div>
    <div class="col" style="padding-left: 0px;">
        <table style="border-spacing: 10px;" class="table table-hover table-striped">
            <thead class="thead-dark">

                <tr>
                    <th>Title</th>
                    <th>Rating</th>
                    <th>Year</th>
                    <th>Genre</th>
                </tr>
            </thead>
            <tbody>
                {% for movie in movies %}
                {% if movie.title %}
                <tr>
                    <td><a href="{% url 'movies:detail' movie.id %}" style="text-decoration:none">{{ movie.title }}</a>
                    </td>
                    <td><strong>{{ movie.rating }}</strong>\10</td>
                    <td>{{ movie.release_year }}</td>
                    <td>{% for mg in movie.genre.all %}. {{ mg }} {% endfor %}</td>
                </tr>
                {% else %}
                <tr>
                    <td class="text-muted">
                        <p>
                            there is no movies in this genre yet :(</p>
                        <a href="#" class="text-reset"></a>All Genres</a>.
                    </td>
                </tr>
                {% endif %}
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
        integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>The Movie world</title>
    <link rel="icon" href="https://i.ibb.co/Q87B3pS/6553141-0.png">
</head>

<body>
    <nav class="navbar navbar-dark bg-dark" style="height: 70px;">
        <a class="navbar-brand" href="{% url 'home' %}"><img src="https://i.ibb.co/Q87B3pS/6553141-0.png" width="35"
                height="35" class="d-inline-block align-top" alt="" loading="lazy">The Movie world</a>
    </nav>


    {% block content %}
    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
        integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
        crossorigin="anonymous"></script>
</body>

</html>